use crate::{
    core::TaskType,
    experts::{Expert, ExpertContext, ExpertResult},
};

pub struct CodeExpert;

impl CodeExpert {
    pub fn cargo_toml(project_name: &str) -> String {
        format!(
            "[package]\nname = \"{project_name}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\n"
        )
    }

    pub fn calculator_lib() -> &'static str {
        "pub fn add(left: i32, right: i32) -> i32 {\n    left + right\n}\n\npub fn subtract(left: i32, right: i32) -> i32 {\n    left - right\n}\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n\n    #[test]\n    fn add_returns_sum() {\n        assert_eq!(add(2, 3), 5);\n    }\n\n    #[test]\n    fn subtract_returns_difference() {\n        assert_eq!(subtract(7, 4), 3);\n    }\n}\n"
    }

    pub fn calculator_main(project_name: &str) -> String {
        format!(
            "use {project_name}::{{add, subtract}};\n\nfn main() {{\n    let sum = add(2, 3);\n    let difference = subtract(7, 4);\n    println!(\"2 + 3 = {{sum}}\");\n    println!(\"7 - 4 = {{difference}}\");\n}}\n"
        )
    }

    pub fn calculator_tests(project_name: &str) -> String {
        format!(
            "use {project_name}::{{add, subtract}};\n\n#[test]\nfn add_works() {{\n    assert_eq!(add(10, 5), 15);\n}}\n\n#[test]\nfn subtract_works() {{\n    assert_eq!(subtract(10, 5), 5);\n}}\n"
        )
    }

    pub fn readme(project_name: &str, prompt: &str) -> String {
        format!(
            "# {project_name}\n\nGenerated by Onyx Brain inside the sandbox.\n\nOriginal goal: {prompt}\n\n## Run\n\n```bash\ncargo run\ncargo test\n```\n"
        )
    }
}

impl Expert for CodeExpert {
    fn name(&self) -> &'static str {
        "CodeExpert"
    }

    fn can_handle(&self, task: &crate::core::Task) -> f32 {
        if matches!(task.task_type, TaskType::Code | TaskType::FileOperation) {
            0.95
        } else {
            0.1
        }
    }

    fn estimate_cost(&self, _task: &crate::core::Task) -> f32 {
        0.4
    }

    fn run(&self, context: &ExpertContext) -> ExpertResult {
        let memory_note = if context.memories.is_empty() {
            "no memory needed".to_string()
        } else {
            format!("used {} relevant memories", context.memories.len())
        };
        ExpertResult {
            expert_name: self.name().to_string(),
            summary: format!("Built a Rust project plan; {memory_note}."),
            suggested_actions: vec!["create_rust_project".to_string(), "cargo_check".to_string()],
            success: true,
            estimated_cost: 0.4,
        }
    }
}
