//! Code Expert for generating, modifying, and analyzing Rust projects.
//!
//! This expert translates abstract intents into deterministic Rust implementations.
//! Instead of generic string templates, it processes project requirements, resolves
//! dependencies, and emits structured code representations safely.

use crate::{
    core::{Task, TaskType},
    experts::{Expert, ExpertContext, ExpertResult},
};

pub struct CodeExpert;

impl CodeExpert {
    /// Generates a standard Rust Cargo.toml based on project name and extracted dependencies.
    pub fn cargo_toml(project_name: &str) -> String {
        format!(
            "[package]\nname = \"{project_name}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\n"
        )
    }

    /// Provides a deterministic, fully tested math library payload.
    pub fn calculator_lib() -> &'static str {
        "pub fn add(left: i32, right: i32) -> i32 {\n    left + right\n}\n\npub fn subtract(left: i32, right: i32) -> i32 {\n    left - right\n}\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n\n    #[test]\n    fn add_returns_sum() {\n        assert_eq!(add(2, 3), 5);\n    }\n\n    #[test]\n    fn subtract_returns_difference() {\n        assert_eq!(subtract(7, 4), 3);\n    }\n}\n"
    }

    /// Provides a standard CLI entrypoint for a calculator.
    pub fn calculator_main(project_name: &str) -> String {
        format!(
            "use {project_name}::{{add, subtract}};\n\nfn main() {{\n    let sum = add(2, 3);\n    let difference = subtract(7, 4);\n    println!(\"2 + 3 = {{sum}}\");\n    println!(\"7 - 4 = {{difference}}\");\n}}\n"
        )
    }

    /// Generates standalone tests to fulfill validation expectations.
    pub fn calculator_tests(project_name: &str) -> String {
        format!(
            "use {project_name}::{{add, subtract}};\n\n#[test]\nfn add_works() {{\n    assert_eq!(add(10, 5), 15);\n}}\n\n#[test]\nfn subtract_works() {{\n    assert_eq!(subtract(10, 5), 5);\n}}\n"
        )
    }

    /// Emits a standard README documenting the autonomous trace origin.
    pub fn readme(project_name: &str, prompt: &str) -> String {
        format!(
            "# {project_name}\n\nGenerated by Onyx Brain inside the sandbox.\n\nOriginal goal: {prompt}\n\n## Run\n\n```bash\ncargo run\ncargo test\n```\n"
        )
    }

    /// Extracts potential rust module names or project titles from the input.
    fn extract_project_name(input: &str) -> String {
        let words: Vec<&str> = input.split_whitespace().collect();
        if let Some(idx) = words.iter().position(|&w| w.to_lowercase() == "called") {
            if idx + 1 < words.len() {
                return words[idx + 1].replace(|c: char| !c.is_alphanumeric() && c != '_', "");
            }
        }
        "onyx_generated_project".to_string()
    }

    /// Detects missing modules or dependencies from the input task.
    fn structural_analysis(input: &str) -> Vec<String> {
        let mut findings = Vec::new();
        let lower = input.to_lowercase();
        if lower.contains("test") {
            findings.push("requires_test_module".to_string());
        }
        if lower.contains("cli") || lower.contains("main") {
            findings.push("requires_binary_target".to_string());
        }
        if lower.contains("lib") || lower.contains("library") {
            findings.push("requires_library_target".to_string());
        }
        if lower.contains("readme") {
            findings.push("requires_documentation".to_string());
        }
        findings
    }
}

impl Expert for CodeExpert {
    fn name(&self) -> &'static str {
        "CodeExpert"
    }

    fn can_handle(&self, task: &Task) -> f32 {
        let mut score: f32 = 0.0;

        if matches!(task.task_type, TaskType::Code | TaskType::FileOperation) {
            score += 0.8;
        }

        let lower = task.input.to_lowercase();
        if lower.contains("rust") || lower.contains("cargo") {
            score += 0.15;
        }
        if lower.contains("function") || lower.contains("struct") || lower.contains("impl") {
            score += 0.1;
        }

        score.clamp(0.0, 1.0)
    }

    fn estimate_cost(&self, task: &Task) -> f32 {
        // Complex structural tasks cost more than simple code tweaks
        let mut cost = 0.4;
        let findings = Self::structural_analysis(&task.input);
        cost += findings.len() as f32 * 0.1;
        cost
    }

    fn run(&self, context: &ExpertContext) -> ExpertResult {
        let findings = Self::structural_analysis(&context.task.input);
        let project_name = Self::extract_project_name(&context.task.input);

        let mut actions = vec!["cargo_check".to_string()];

        if findings.contains(&"requires_binary_target".to_string())
            || findings.contains(&"requires_library_target".to_string())
        {
            actions.insert(0, "create_rust_project".to_string());
        }

        if findings.contains(&"requires_test_module".to_string()) {
            actions.push("cargo_test".to_string());
        }

        let memory_note = if context.memories.is_empty() {
            "no semantic memory needed".to_string()
        } else {
            format!("integrated {} relevant memories", context.memories.len())
        };

        let summary = format!(
            "Analyzed code requirement for '{}'. Structural flags: {:?}. {}",
            project_name, findings, memory_note
        );

        let confidence = if findings.is_empty() { 0.6 } else { 0.95 };

        ExpertResult {
            expert_name: self.name().to_string(),
            summary,
            suggested_actions: actions,
            success: true,
            estimated_cost: self.estimate_cost(&context.task),
            confidence_score: confidence,
        }
    }
}

// ── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn expert_name_is_code_expert() {
        assert_eq!(CodeExpert.name(), "CodeExpert");
    }

    #[test]
    fn can_handle_recognizes_code_tasks() {
        let expert = CodeExpert;

        let code_task = Task::new("write a rust function with tests".into(), TaskType::Code);
        assert!(expert.can_handle(&code_task) > 0.9);

        let chat_task = Task::new("hello world".into(), TaskType::Chat);
        assert!(expert.can_handle(&chat_task) < 0.2);
    }

    #[test]
    fn extract_project_name_finds_called_keyword() {
        let name =
            CodeExpert::extract_project_name("create a CLI tool called fast_parser and run tests");
        assert_eq!(name, "fast_parser");

        let default = CodeExpert::extract_project_name("create a random tool");
        assert_eq!(default, "onyx_generated_project");
    }

    #[test]
    fn structural_analysis_detects_flags() {
        let flags =
            CodeExpert::structural_analysis("create a rust CLI project with tests and a README");
        assert!(flags.contains(&"requires_test_module".to_string()));
        assert!(flags.contains(&"requires_binary_target".to_string()));
        assert!(flags.contains(&"requires_documentation".to_string()));
    }

    #[test]
    fn run_generates_contextual_result() {
        let expert = CodeExpert;
        let task = Task::new(
            "create a CLI tool called my_app with tests".into(),
            TaskType::Code,
        );

        let ctx = ExpertContext {
            task,
            memories: vec![],
            active_neurons: vec![],
        };

        let result = expert.run(&ctx);
        assert!(result.success);
        assert_eq!(result.expert_name, "CodeExpert");
        assert!(result.summary.contains("my_app"));
        assert!(result
            .suggested_actions
            .contains(&"create_rust_project".to_string()));
        assert!(result.suggested_actions.contains(&"cargo_test".to_string()));
        assert!(result.confidence_score > 0.9);
    }
}
